INSERT INTO `category` (name, description) VALUES ('Gathering', 'These are gathering machines');
INSERT INTO `category` (name, description) VALUES ('Transport', 'These are transport machines');
INSERT INTO `category` (name, description) VALUES ('Maintenance', 'These are maintenance machines');
INSERT INTO `category` (name, description) VALUES ('Sport', 'These are sport vehicles');
INSERT INTO `category` (name, description) VALUES ('Upcoming', 'These are sport machines');

INSERT INTO `product` (name, description, price, image_url, category_id) VALUES ('CROFTER', 'The most efficient multi-breed specialised crop harvester for your industry', 4000000000, 'https://www.geek-art.net/wp-content/uploads/2021/01/hamish-frater-bulldoser.jpg', (SELECT `id` FROM `category` WHERE `name` = 'Gathering'));
INSERT INTO `product` (name, description, price, image_url, category_id) VALUES ('MINER', 'The most heavy duty industrial excavating machine for your industry', 7000000000, 'https://www.geek-art.net/wp-content/uploads/2021/01/hamish-frater-machine01-portrait-final.jpg', (SELECT `id` FROM `category` WHERE `name` = 'Gathering'));
INSERT INTO `product` (name, description, price, image_url, category_id) VALUES ('LUMBERER', 'The ultimate portable deforestation solution, shiver inducing amongst all green conservativists', 30000000, 'https://cdna.artstation.com/p/assets/images/images/016/507/676/large/hamish-frater-lumberjack05.jpg', (SELECT `id` FROM `category` WHERE `name` = 'Gathering'));

INSERT INTO `product` (name, description, price, image_url, category_id) VALUES ('BARGE', 'This heavy duty transport ship is meant for cross planet cargo deliveries of interplanetary scale', 9000000000, 'https://www.geek-art.net/wp-content/uploads/2021/01/hamish-frater-flyingbardge03.jpg', (SELECT `id` FROM `category` WHERE `name` = 'Transport'));
INSERT INTO `product` (name, description, price, image_url, category_id) VALUES ('WALKER', 'This land traveling giant is great for traversing landscapes for extended periods of time', 800000, 'https://www.geek-art.net/wp-content/uploads/2021/01/hamish-frater-20200627-001407.jpg', (SELECT `id` FROM `category` WHERE `name` = 'Transport'));
INSERT INTO `product` (name, description, price, image_url, category_id) VALUES ('WALKER MINI', 'The walker mini provides the comfort of a walker at a much smaller profile', 200000, 'https://www.geek-art.net/wp-content/uploads/2021/01/hamish-frater-20200303-190709.jpg', (SELECT `id` FROM `category` WHERE `name` = 'Transport'));
INSERT INTO `product` (name, description, price, image_url, category_id) VALUES ('STROLLER', 'This all round portable storage barge gets your goods from anywhere, to anywhere in a reasonable amount of time', 10000, 'https://www.geek-art.net/wp-content/uploads/2021/01/hamish-frater-transportwalker03-planet-sm.jpg', (SELECT `id` FROM `category` WHERE `name` = 'Transport'));

INSERT INTO `product` (name, description, price, image_url, category_id) VALUES ('SOLDER', 'This all round portable storage barge gets your goods from anywhere, to anywhere in a reasonable amount of time', 200000, 'https://www.geek-art.net/wp-content/uploads/2021/01/hamish-frater-gorilla.jpg', (SELECT `id` FROM `category` WHERE `name` = 'Maintenance'));
INSERT INTO `product` (name, description, price, image_url, category_id) VALUES ('BUILDER', 'This mobile construction site is meant for those who want their architectural projects finished', 180000, 'https://www.geek-art.net/wp-content/uploads/2021/01/hamish-frater-deserttraider.jpg', (SELECT `id` FROM `category` WHERE `name` = 'Maintenance'));
INSERT INTO `product` (name, description, price, image_url, category_id) VALUES ('FUELER', 'This mobile fuel station is the backbone of your project. It is able to fuel all IAC machines', 230000, 'https://cdnb.artstation.com/p/assets/images/images/048/905/113/large/hamish-frater-mediumsalvage02-sm.jpg', (SELECT `id` FROM `category` WHERE `name` = 'Maintenance'));

INSERT INTO `product` (name, description, price, image_url, category_id) VALUES ('RACER', 'This joyous ride is for speedy business travel. It might also get used for fun on the weekends', 750000, 'https://www.geek-art.net/wp-content/uploads/2021/01/hamish-frater-speeder02.jpg', (SELECT `id` FROM `category` WHERE `name` = 'Sport'));

INSERT INTO `product` (name, description, price, image_url, category_id) VALUES ('COOKER', 'This upcoming wonder removes the need for central processing facilities. Bringing material processing to wherever is needed', 650000, 'https://cdnb.artstation.com/p/assets/images/images/053/237/045/4k/hamish-frater-cauldron-final.jpg', (SELECT `id` FROM `category` WHERE `name` = 'Upcoming'));